### ISSUE TITLE
Pre-commit issue

### ISSUE THREAD

**Issue by PixelTom** [daviseford/aos-reminders#80]
Getting this error on a pre-commit when starting my KO branch:

```
~/x/aos-reminders git:feature/kharadron ❯❯❯ git commit -am 'Init KO'                                                                                                                                                                        ✚
husky > pre-commit (node v10.15.0)
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'replace-in-file'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/pixeltom/x_work/aos-reminders/clean.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by daviseford** [comment]
Run `yarn`.

**Comment by daviseford** [comment]
I added a new dependency

**Comment by PixelTom** [comment]
When in doubt, run `yarn` first!!

Thanks mate.
